### ISSUE TITLE
sqlx库使用指南 | 李文周的博客

### ISSUE THREAD

**Issue by Q1mi** [Q1mi/BlogComments#113]
https://www.liwenzhou.com/posts/Go/sqlx/ 

 李文周的Blog database/sql mysql sqlx 批量插入 bulk insert query in select in order by find_in_set batch insert

**Comment by lsq51201314** [comment]
您好老师，enum类型的数据如何操作呢，查询到的资料操作总是不成功。

**Comment by c-jf** [comment]
可以批量更新么

**Comment by Q1mi** [comment]
> @c-jf
> 可以批量更新么

update 不可以吗？

**Comment by DaiRenQiang** [comment]
对像性别一类的返回0/1的字段如何处理。处理后转成男/女

**Comment by jasonneverstop** [comment]
请问sqlx库连接数据库后，为什么不用defer db.Close()

**Comment by LTY233333** [comment]
在事务操作内个部分 `sqlStr2 := "Update user set age=50 where i=?"` 貌似少个d，
是不是应该是 `sqlStr2 := "Update user set age=50 where id=?"`
