### ISSUE TITLE
[译]关于切片操作的技巧 | 李文周的博客

### ISSUE THREAD

**Issue by Q1mi** [Q1mi/BlogComments#131]
https://www.liwenzhou.com/posts/Go/slice_tricks/ 

 李文周 博客 Blog Go语言教程 go 教程 切片 技巧 slice copy delete cut append insert 插入 追加

**Comment by 471909488** [comment]
ttttttttttttttttttttt

**Comment by 471909488** [comment]
ttttttttttttttttttttt

**Comment by 1974410167** [comment]
感觉可以写一个切片库，实现类似python的remove insert pop 等函数，go这切片操作舒适是丑
