### ISSUE TITLE
Go语言基础之time包 | 李文周的博客

### ISSUE THREAD

**Issue by Q1mi** [Q1mi/BlogComments#148]
https://www.liwenzhou.com/posts/Go/go-time/ 

 李文周的 Blog 提供 Go 语言中文教程,李文周博客,Go 语言学习之路是我整理的一个免费教程和视频教程，也是Go语言的入门教程，非常适合新手入门学习go语言。本文介绍了time包对时区、时间格式化、解析时间等操作。

**Comment by tangqihan** [comment]
func main() {
	now := time.Now()
	fmt.Println(now.Format("2006/01/02 15:04:05"))
	t := time.Now()
	for i := 0; i < 10; i++ {
		fmt.Println(i)
		u := time.Now()
		w := u.Sub(t)
		fmt.Println(w * 1000)
	}
}

**Comment by Tim3Triver** [comment]
func main() {
	//formatDemo()

	//parseDemo()
	execTime(test1)
}

func test1() {
	now := time.Now()
	nowtime := now.Format("2006/01/02 15:04:05")
	fmt.Println(nowtime)
}

func execTime(x func()) {

	start := time.Now()
	x()
	sub := time.Now().Sub(start)

	fmt.Println(time.Since(start))
	fmt.Printf("执行总时间 %v微秒\n", int(sub)/1000)
}

**Comment by Tim3Triver** [comment]
```go
func main() {
	//formatDemo()

	//parseDemo()
	execTime(test1)
}

func test1() {
	now := time.Now()
	nowtime := now.Format("2006/01/02 15:04:05")
	fmt.Println(nowtime)
}

func execTime(x func()) {

	start := time.Now()
	x()
	sub := time.Now().Sub(start)

	fmt.Println(time.Since(start))
	fmt.Printf("执行总时间 %v微秒\n", int(sub)/1000)
}
/* 执行结果
2022/03/30 16:48:55
29.2194ms           
执行总时间 29219微秒
*/
```
