### ISSUE TITLE
Go语言基础之time包 | 李文周的博客

### ISSUE THREAD

**Issue by Q1mi** [Q1mi/BlogComments#15]
https://www.liwenzhou.com/posts/Go/go_time/ 

 李文周的Blog

**Comment by 272909106** [comment]
```golang
package main

import (
	"fmt"
	"time"
)

func main() {
	start := time.Now()
	now := time.Now().Format("2006/01/02 15:04:05")
	fmt.Println(now)
	end := time.Now()
	last := end.Sub(start) / 1e3
	fmt.Println(last)
}

```

**Comment by why0210** [comment]
//获取当前时间，格式化输出为2017/06/19 20:30:05`格式
package main

import "fmt"
import "time"

func main() {
	t := time.Now()
	fmt.Println("t=", t.Format("2006/01/02 15:04:05"))
}

**Comment by why0210** [comment]
//获取当前时间，格式化输出为2017/06/19 20:30:05`格式
package main

import "fmt"
import "time"

func main() {
	t := time.Now()
	fmt.Println("t=", t.Format("2006/01/02 15:04:05"))
}

**Comment by yusonghu** [comment]
## 2016-01-02 03:04:05 程序员的浪漫可还行

**Comment by SherlockGy** [comment]
这还真的不是Go诞生的时间哦，Go诞生于2009年11月10日。而那个格式化串是按照美国人好记忆的日期书写顺序写的一个1234567。1月2号下午3时4分5秒 06年 7时区

**Comment by xjb714** [comment]
```
func homework(){
	fmt.Println(time.Now().Format("2006/01/02 15:04:05"))//2021/01/24 22:53:47
	before:=time.Now().UnixNano()
	for i:=0;i<=1000000;i++{}
	after:=time.Now().UnixNano()
	fmt.Println(before)//1611500027278004900
	fmt.Println(after)//1611500027278994000
	fmt.Println((after-before)/1000)//989
}

**Comment by xujiaxindudu** [comment]
package main

import (
	"fmt"
	"time"
)

func main() {
	now := time.Now()
	// fmt.Println(now)
	// // fmt.Println(now.Format("2006-01-02 15:04:05.000 Mon Jan"))
	// a := now.Format("2006-01-02 15:04:05")
	// fmt.Println(a)
	startTime := now.UnixNano()
	sum := 0
	for i := 0; i <= 100000000; i++ {
		sum = sum + 1
	}
	endTime := now.UnixNano()
	fmt.Println((endTime - startTime) / 1000000)
	fmt.Println(sum)
}
