### ISSUE TITLE
gRPC中的名称解析和负载均衡 | 李文周的博客

### ISSUE THREAD

**Issue by Q1mi** [Q1mi/BlogComments#170]
https://www.liwenzhou.com/posts/Go/name-resolving-and-load-balancing-in-grpc/ 

 李文周的Blog提供免费的全套Go语言学习教程。本文介绍了gRPC中的名称解析和负载均衡设计，包括gRPC客户端如何通过name resolver获取服务端的可用地址，如何使用pick_first和round_robin策略选取服务端。

**Comment by darron08** [comment]
请问producer中的for循环不可以是无限循环吗？

**Comment by YM-FANG** [comment]
消费的代码里面，forever 为啥能阻塞主进程呢？不是应该报死锁吗

**Comment by c-jf** [comment]
安装 gRPC-Gateway那里好像要用go install才行，我试了下 go get执行make gen 会报错找不到程序
