### ISSUE TITLE
go-elasticsearch使用指南 | 李文周的博客

### ISSUE THREAD

**Issue by Q1mi** [Q1mi/BlogComments#220]
https://www.liwenzhou.com/posts/Go/go-elasticsearch/ 

 李文周的 Blog 提供 Go 语言中文教程,李文周博客,Go 语言学习之路是我整理的一个免费教程，包含部分视频教程，也是非常适合新手学习Go语言的入门教程。本文介绍了如何使用elasticsearch 官方的 go 客户端—— go-elasticsearch。包括如何创建索引、创建文档和如何进行模糊查询搜索、如何聚合搜索等。

**Comment by itwangxiaobai** [comment]
// 可以使用异或运算符进行计算，异或运算符有一个很好的性质：任何数和0做异或都是原来的数，任何数和本身做异或运算都是0.所以
// 我们可以将所有的数进行异或运算，这样，相同的数会进行抵消。只留下唯一出现的数
package main

import "fmt"

func singleNumber(nums []int) int {
	result := 0
	for _, num := range nums {
		result ^= num
	}
	return result
}

func main() {
	nums := []int{4, 2, 3, 2, 3}
	fmt.Println(singleNumber(nums))
}
