### ISSUE TITLE
Jaeger快速指南 | 李文周的博客

### ISSUE THREAD

**Issue by Q1mi** [Q1mi/BlogComments#226]
https://www.liwenzhou.com/posts/Go/jaeger/ 

 李文周的 Blog 提供 Go 语言中文教程,李文周博客,Go 语言学习之路是我整理的一个免费教程，包含部分视频教程，也是非常适合新手学习Go语言的入门教程。本文介绍了社区中非常热门的分布式追踪解决方案——jaeger，并编写一个Go语言demo，生成 trace 和 span 数据上报至 Jaeger。

**Comment by JackSinner** [comment]
grpc 使用了证书,并且使用了grpc_health_v1作为健康检查，consul需要配置 证书吗？
