### ISSUE TITLE
zap日志库配置链路追踪 | 李文周的博客

### ISSUE THREAD

**Issue by Q1mi** [Q1mi/BlogComments#233]
https://www.liwenzhou.com/posts/Go/zap-otel/ 

 李文周的 Blog 提供 Go 语言中文教程,李文周博客,Go 语言学习之路是我整理的一个免费教程，包含部分视频教程，也是非常适合新手学习Go语言的入门教程。本文介绍了 Go 语言 zap日志库如何配置链路追踪，以及如何在日志中记录traceID。

**Comment by loonghe** [comment]
文中grpc和http使用同一个端口启动服务，如何将http请求的headers塞进context上下文中
