### ISSUE TITLE
Go语言中的单例模式 | 李文周的博客

### ISSUE THREAD

**Issue by Q1mi** [Q1mi/BlogComments#67]
https://www.liwenzhou.com/posts/Go/singleton_in_go/ 

 李文周的Blog Go语言教程 golang中文教程 李文周博客 七米 qimi Go语言并发 并发元语 goroutine sync 单例模式 并发安全 singleton 设计模式

**Comment by evanzme** [comment]
单例模式使用
once.Do(func() {
    instance = &singleton{}
})
如果在并发场景下，第一个初始化失败了，后面就再也不会执行了，这个问题是不是也需要处理一下？

**Comment by wjhtime** [comment]
if initialized == 0 {
         instance = &singleton{}
         atomic.StoreUint32(&initialized, 1)
    }
为什么不是 if atomic.LoadUInt32(&initialized) == 0
